services:
  keycloak-postgres:
    image: library/postgres:${KC_POSTGRES_IMAGE_TAG}
    container_name: ${KC_POSTGRES_CONTAINER_NAME}
    restart: on-failure
    environment:
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KC_POSTGRES_DB}
    healthcheck:
      test: pg_isready -d ${KC_POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${KC_POSTGRES_PORT_MAPPING}:5432
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    entrypoint: ["/opt/keycloak/entrypoint.sh"]
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_FEATURES: ${KC_FEATURES}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

    volumes:
      - ./entrypoint.sh:/opt/keycloak/entrypoint.sh
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - ${KC_PORT_MAPPING}:8080
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  postgres-auth-service:
    container_name: postgres-auth-service
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT_MAPPING}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge